// src/client/components/PlayButton.vue
<template>
  <button className={ 'play-button' } v-on:click="togglePlay">
    play button yo
  </button>
</template>

<script>
  export default {
    methods: {
      togglePlay: function() {
        var playing = !this.props.transport.get('play');
        this.props.dispatch(setPlay(playing));
      }
    }
  }
</script>

// src/client/components/PlayButton.jsx
import React, { Component } from 'react';
import classNames from 'classnames';
import { setPlay } from '../actions';

class PlayButton extends Component {
  constructor(props) {
    super(props);
    this.togglePlay = this.togglePlay.bind(this);
  }

  togglePlay() {
    var playing = !this.props.transport.get('play');
    this.props.dispatch(setPlay(playing));
  }

  render() {
    return (
      <button className={ 'play-button' } onClick={ this.togglePlay }>
        play button yo
      </button>
    );
  }
}

export default PlayButton;
