// src/client/containers/Scene.jsx
/** 
 * ASCII art!
**/
import React from 'react';

import { connect } from 'react-redux';

const Scene = ({ layers, gridCSS }) => (
  <section className={'scene'}>
    Scene!!!
  </section>
);

function mapStateToProps(store) {
  return {
    store
  };
}

export default connect(mapStateToProps)(Scene);

// src/client/components/Scene.vue
<style scoped lang="sass">
  .scene{
    height: 100%;
    position: fixed;
  }
</style>

<template>
	<section class="scene">
    Scene!
  </section>
</template>

<script>
  import store from '../vuex/store';

  export default {
    store,
    vuex: {
      getters: {
        layers: store => store.layers
      }
    }
  }
</script>
