// src/client/containers/Scheduler.jsx
/** 
 * Scedules events from store "events". Read only!!!!.
**/
import React from 'react';
import Css from '../destinations/css.js';
import { connect } from 'react-redux';
import { clone, sortBy } from 'lodash';

/**
 * @class Scheduler
 * A sequencer using audio context for timing.
 * @author choshun.snyder@gmail.com (Choshun Snyder)
 */
class SchedulerUtils {
  /**
   * @constructor Scheduler
   * @param {Object} cube cube object to schedule
   */
  constructor() {

    this.sequence;

    this.transport;

    this.destination = new Css();

    /**
     * Interval to try and refire schedule.
     * @type {Number} in ms
     */
    this.lookahead = 30;

    /**
     * Time to look ahead in sequence to schedule.
     * @type {Number} in sec (audio context is in seconds)
     */
    this.scheduleAheadTime = 0.1;

    /**
     * Index of scheduled events.
     * @type {Number}
     */
    this.index = 0;
    this.measureTime = 0;
  }

  init(sequence, transport) {
    this.setSequence(sequence);
    this.setTransport(transport);
    this.context = this.transport.context;
    this.destination.init();
  }

  // Converts Immutable object to array sorted by time.
  setSequence(sequence) {
    this.sequence = _.sortBy(_.clone(sequence.toArray()), 'time');
  }

  setTransport(transport) {
    this.transport = _.clone(transport.toObject());
  }

  /**
   * Scheduler for sequence of events. Fires a destination
   * based on event time in store "events". Ideally this is destination agnostic,
   * this same scheduler should be able to trigger anything, css, canvas, web audio etc.
   * solely based on event data.
   * It's a scheduler, so there's a lookahead and all that other good stuff:
   * http://www.html5rocks.com/en/tutorials/audio/scheduling/
   */

  // TODO: BUG: if I put an event really far right of the grid, current measure time skips
  // to the next measure.
  schedule() {
    let nextEvent,
        eventTime;

    if (this.sequence && this.transport) {
      nextEvent = this.sequence[this.index];
      eventTime = nextEvent.time * this.transport.time;

      // See article above.
      if ((eventTime + this.measureTime) < (this.context.currentTime +
        this.scheduleAheadTime)) {
        this.index = ((this.index + 1) % this.sequence.length);

        // Fires event callback.
        this.destination[nextEvent.callback](nextEvent);

        // Reset event loop to current time.
        if (this.index === 0 ) {
          this.measureTime = (((Math.floor((this.context.currentTime + this.scheduleAheadTime) / this.transport.time)) * this.transport.time) + this.transport.time);
        }
      }
    }

    this.cycle();
  }

  cycle() {
    // Never not polling.
    window.setTimeout(() => {
      if (this.transport && this.transport.play === true) {
        this.schedule();
      }
    }, this.lookahead);
  }

  mapStateToProps(store) {
    return {
      sequence: store.events,
      transport: store.transport
    };
  }
}

const schedulerUtils = new SchedulerUtils();
// Starts scheduling once, not every time sequence/transport changes.
schedulerUtils.schedule();

const Scheduler = ({ sequence, transport }) => (
  <section className={'scheduler'}>
    Scheduler!!!

    // TODO: this fires every time store changes, only set sequence and transport here.
    { schedulerUtils.init(sequence, transport) }
  </section>
);

export default connect(schedulerUtils.mapStateToProps)(Scheduler);

// sequence/src/components/Scheduler.vue
<script>
  import store from '../vuex/store';
  import Css from '../destinations/css.js';
  import ContextUtils from '../utils/context-utils.js';
  import { clone, cloneDeep, findIndex, slice, forEach } from 'lodash';

  // TODO: Put in vue component.
  const contextUtils = new ContextUtils();

  export default {
    store,
    data () {
      return {

        /**
         * Destination callback.
         * @type {Function}
         */
        destination: () => new Css(),

        /**
         * Amount to poll for changes in store.sequence (in ms).
         * @type {Number}
         */
        lookahead: 30,

        /**
         * Amount to look ahead from currentTime 
         * (in percentage of 1 - the total sequence time).
         * @type {Number}
         */
        scheduleAheadTime: 0.01,

        /**
         * Current event scheduled.
         * @type {Number}
         */
        index: 0,

        /**
         * Length of scheduled sequence.
         * @type {Number}
         */
        length: 0,

        /**
         * Flag so the same event isn't fired twice in a row.
         * @type {Number}
         */
        firedEventTime: 0,

        /**
         * Reference to the scheduler timeout, so we can
         * make sure it's cleared if it's reinstantiated by mistake.
         * @type {Function}
         */
        scheduleTimeout: undefined
      }
    },
    vuex: {
      getters: {

        /**
         * Ordered sequence from store.
         * @type {Array}
         */
        sequence: store => {
          return _.cloneDeep(store.sequence.sort((a, b) => {
            return a.time - b.time;
          }));
        },

        /**
         * Transport from store.
         * @type {Object}
         */
        transport: store => store.transport
      }
    },
    methods: {

      /**
       * Schedules events and fires the destination callback.
       */
      schedule () {
        if (this.transport.playing) {
          let time = contextUtils.getTranslatedContext(this.transport);

          this.index = this.getNextIndex(this.sequence, this.transport, time);

          if (this.index !== -1) {
            let nextEvent = this.sequence[this.index];
            let eventTime = nextEvent.time;

            // The infamous article explaining the following:
            // http://www.html5rocks.com/en/tutorials/audio/scheduling/
            if (eventTime !== this.firedEventTime && eventTime < time + this.scheduleAheadTime) {
              this.length = this.sequence.length;

              let reset = (this.index === this.length);
              // Fires event callback.
              this.destination()[nextEvent.callback](nextEvent, reset);

              this.firedEventTime = eventTime;
            }
          }
        }

        this.cycle();
      },

      /**
       * Never not polling.
       */
      cycle () {
        if (this.scheduleTimeout) {
          clearTimeout(this.scheduleTimeout);
        }

        this.scheduleTimeout = window.setTimeout(() => {
          this.schedule();
        }, this.lookahead);
      },

      /**
       * Finds the next event based on transport time.
       * @param {Array} sequence Sequence shared in store.
       * @param {Object} transport Transport object in store.
       * @param {Number} time Current time.
       * @return {Number} Index of next event. 
       */
      getNextIndex (sequence, transport, time) {
        return _.findIndex(sequence, (event) => {
          return event.time + this.scheduleAheadTime > time;
        });
      }
    },
    ready () {
      // Kick off the polling.
      this.schedule(); 
    }
  }
</script>
